### PR TITLE
Bug fixes and Nuclei update

### PR DESCRIPTION
**Pull request by ehsandeep**
- [x] Fixed a bug with multiple CLI input support
```yaml
        with:
          urls: urls.txt
          flags: "-severity critical,high,medium,low -stats"
```
- [x] Fixed a bug with config file input support
- [x] Back to the default template path
- [x] Added support for issue reporting config input

```yaml
        with:
          urls: urls.txt
          config: nuclei-config.yaml
          report-config: issue-config.yaml
```

### CODE REVIEW

**Review by toufik-airane — APPROVED** [review]
Dear @ehsandeep,

Are sure you want to remove the possibility to set the user-agent ?

Best.

**Comment by ehsandeep** [comment]
@toufik-airane I thought it would be fine, as we can still do the same with `flags` and within the config file itself, let me know if you think we should still keep it?

**Comment by toufik-airane** [comment]
I think to smooth the user experience, we should write few words on **how to set a user-agent**.
It's an important setting for company in order to monitoring continuous security scanning with SIEM.

Let's document the setting.

**Comment by ehsandeep** [comment]
Thank you @toufik-airane for the review, I've added UA support back and added a working example in the readme.

**Pull request merged**
